name: porocci_main
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter    
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  flutter_riverpod: ^2.1.1

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  image_picker: ^0.8.6
  qr_flutter: ^4.0.0
  mobile_scanner: ^2.1.0
  flutter_beep: ^1.0.0
  flutter_vibrate: ^1.3.0
  wakelock: ^0.6.2
  firebase_storage: ^11.0.7
  path: ^1.8.2
  palestine_console: ^0.0.10
  shared_preferences: ^2.0.15
  go_router: ^6.0.0
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4

  
flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/auth_icons/
    - assets/images/hero/
    - assets/images/logo/