// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5T7Xg9N37_okZWR94TxjTQu_fpCqRYgQ',
    appId: '1:68965189012:web:1977a6b15fe365f7253b81',
    messagingSenderId: '68965189012',
    projectId: 'porochi-app-b37af',
    authDomain: 'porochi-app-b37af.firebaseapp.com',
    storageBucket: 'porochi-app-b37af.appspot.com',
    measurementId: 'G-SVQBYM61J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxMIm4gnTUufhIO4EENeKu_R0IGXRikLk',
    appId: '1:68965189012:android:9ad1d56c4d497ca6253b81',
    messagingSenderId: '68965189012',
    projectId: 'porochi-app-b37af',
    storageBucket: 'porochi-app-b37af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiWTzKIOxN0dtCznAeWQ6T0yqfGp0Jlt8',
    appId: '1:68965189012:ios:88e5d6e97a9d3197253b81',
    messagingSenderId: '68965189012',
    projectId: 'porochi-app-b37af',
    storageBucket: 'porochi-app-b37af.appspot.com',
    iosClientId: '68965189012-ok7ildeqvmmal92q8lu0ji0ini6j6m78.apps.googleusercontent.com',
    iosBundleId: 'com.example.keypetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiWTzKIOxN0dtCznAeWQ6T0yqfGp0Jlt8',
    appId: '1:68965189012:ios:88e5d6e97a9d3197253b81',
    messagingSenderId: '68965189012',
    projectId: 'porochi-app-b37af',
    storageBucket: 'porochi-app-b37af.appspot.com',
    iosClientId: '68965189012-ok7ildeqvmmal92q8lu0ji0ini6j6m78.apps.googleusercontent.com',
    iosBundleId: 'com.example.keypetApp',
  );
}
